#!/usr/bin/env python
import simplejson as json
import urlparse
import os
import auth
import memcache
import sqlite3

if __name__ == "__main__":
  # Parse the path
  qwargs = urlparse.parse_qs(os.environ["QUERY_STRING"])

  # Enforce one value per query string argument
  for key in qwargs:
    qwargs[key] = qwargs[key][0]
  
  # Initialize our memcache client
  cache = memcache.Client(["localhost:11211"], debug=0)
  
  # Initialize our database connection
  conn = sqlite3.connect("teams.db")
  c = conn.cursor()

  # Get the session key for this user
  key = auth.dehexify(cache.get("__SRP_SESSKEY:" + qwargs["uname"]))
  
  info = json.loads(auth.decrypt(key, qwargs["info"]))
  
  # Get the teams belonging to this user
  c.execute("UPDATE teams SET name=?, members=? WHERE id=?", (info["name"], json.dumps(info["members"]), info["id"]))
  conn.commit()
  
  print "content-type: application/json"
  print ""
  print json.dumps({
      "success": True if c.rowcount == 1 else False
  })
